import axios from "axios";
import { articleService, videoService, faqService } from "../lib/contentService";

// Configure axios
axios.defaults.baseURL = import.meta.env.VITE_API_URL || "http://localhost:5000";

// Add auth token to requests if available
axios.interceptors.request.use((config) => {
  const token = localStorage.getItem("adminToken");
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Mock data for videos and FAQs (will be migrated to Firestore later)
const mockVideos = [
  {
    id: "1",
    title: "Quick Start Tutorial",
    category: "Getting Started",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    description: "A 5-minute overview of key features",
    transcript: "Welcome to our quick start tutorial. In this video, we'll cover...",
    createdAt: new Date().toISOString(),
    views: 3200,
  },
  {
    id: "2",
    title: "Advanced Configuration",
    category: "Features",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    description: "Deep dive into configuration options",
    transcript: "In this advanced tutorial, we'll explore configuration settings...",
    createdAt: new Date().toISOString(),
    views: 1500,
  },
];

const mockFAQs = [
  {
    id: "1",
    question: "How do I reset my password?",
    answer: "You can reset your password by clicking the 'Forgot Password' link on the login page.",
    category: "Account",
    order: 1,
  },
  {
    id: "2",
    question: "What payment methods do you accept?",
    answer: "We accept all major credit cards, PayPal, and bank transfers for enterprise customers.",
    category: "Billing",
    order: 2,
  },
  {
    id: "3",
    question: "How can I contact support?",
    answer: "You can reach our support team via email, chat, or by creating a support ticket in your dashboard.",
    category: "Support",
    order: 3,
  },
];

// Public API calls - now using Firestore database for articles
export const getArticles = async () => {
  try {
    const articles = await articleService.getByStatus('published');
    return { data: articles };
  } catch (error) {
    console.error('Error fetching articles:', error);
    return { data: [] };
  }
};

export const getArticleById = async (id: string) => {
  try {
    const article = await articleService.getById(id);
    return { data: article };
  } catch (error) {
    console.error('Error fetching article:', error);
    return { data: null };
  }
};

export const getVideos = () => {
  // return axios.get("/api/videos");
  return Promise.resolve({ data: mockVideos });
};

export const getFAQs = () => {
  // return axios.get("/api/faqs");
  return Promise.resolve({ data: mockFAQs });
};

export const postFeedback = (data: any) => {
  // return axios.post("/api/feedback", data);
  return Promise.resolve({ data: { success: true } });
};

export const searchContent = async (query: string) => {
  try {
    // Get all published articles from Firestore
    const articles = await articleService.getByStatus('published');
    
    // Search through articles with enhanced filtering
    const searchResults = articles.filter((article: any) => {
      const searchLower = query.toLowerCase();
      
      // Search in title
      if (article.title?.toLowerCase().includes(searchLower)) return true;
      
      // Search in content (strip HTML tags)
      const plainContent = article.content?.replace(/<[^>]*>/g, '').toLowerCase() || '';
      if (plainContent.includes(searchLower)) return true;
      
      // Search in keywords (auto-generated by system)
      if (article.keywords?.some((keyword: string) => keyword.toLowerCase().includes(searchLower))) return true;
      
      // Search in tags
      if (article.tags?.some((tag: string) => tag.toLowerCase().includes(searchLower))) return true;
      
      // Search in category
      if (article.category?.toLowerCase().includes(searchLower)) return true;
      
      // Search in author
      if (article.author?.toLowerCase().includes(searchLower)) return true;
      
      return false;
    });
    
    // For now, return mock videos and FAQs until they're also migrated to Firestore
    const videoResults = mockVideos.filter((v) =>
      v.title.toLowerCase().includes(query.toLowerCase()) ||
      v.description.toLowerCase().includes(query.toLowerCase())
    );
    
    const faqResults = mockFAQs.filter((f) =>
      f.question.toLowerCase().includes(query.toLowerCase()) ||
      f.answer.toLowerCase().includes(query.toLowerCase())
    );
    
    return {
      data: {
        articles: searchResults,
        videos: videoResults,
        faqs: faqResults,
      }
    };
  } catch (error) {
    console.error('Error searching content:', error);
    return {
      data: {
        articles: [],
        videos: [],
        faqs: [],
      }
    };
  }
};

// Admin API calls
export const loginAdmin = (credentials: { email: string; password: string }) => {
  // return axios.post("/api/admin/login", credentials);
  // Mock login - accepts any email/password
  const mockToken = "mock-admin-token-123";
  return Promise.resolve({ data: { token: mockToken, user: { email: credentials.email } } });
};

export const createArticle = (data: any) => {
  return axios.post("/api/admin/articles", data);
};

export const updateArticle = (id: string, data: any) => {
  return axios.put(`/api/admin/articles/${id}`, data);
};

export const deleteArticle = (id: string) => {
  return axios.delete(`/api/admin/articles/${id}`);
};

export const createVideo = (data: any) => {
  return axios.post("/api/admin/videos", data);
};

export const updateVideo = (id: string, data: any) => {
  return axios.put(`/api/admin/videos/${id}`, data);
};

export const deleteVideo = (id: string) => {
  return axios.delete(`/api/admin/videos/${id}`);
};

export const createFAQ = (data: any) => {
  return axios.post("/api/admin/faqs", data);
};

export const updateFAQ = (id: string, data: any) => {
  return axios.put(`/api/admin/faqs/${id}`, data);
};

export const deleteFAQ = (id: string) => {
  return axios.delete(`/api/admin/faqs/${id}`);
};

export const getFeedbacks = () => {
  return axios.get("/api/admin/feedbacks");
};
